### ISSUE TITLE
Header logo

### ISSUE THREAD

**Issue by Gianfranco97** [aethonan/aethonan.github.io#1]
Hi, @ajsb85 

In its logo located in the header had the following problems:

1. was slightly misaligned
![screenshot_57](https://user-images.githubusercontent.com/19965590/30529144-5f35a52e-9c08-11e7-8004-d7574df8d571.png)

2. did not resize
![screenshot_55](https://user-images.githubusercontent.com/19965590/30529152-710dd49c-9c08-11e7-98f8-431c3bf6a933.png)

I have solved the problems, I do not send the code through a PR because, if I am not mistaken, this site is generated through a template, a template to which I have no access.

solve the problem is simple, just add a class of CSS to your image (in my case use "logo") and add the following CSS code into your project:

``` css
@media (max-width: 1084px) { 
    .logo {
        height: 30px;
        margin-top: -3.5px;
    }
}
@media (min-width: 1084px) { 
    .logo {
        margin-top: -1.5px;
    }
}
```
![screenshot_59](https://user-images.githubusercontent.com/19965590/30529171-ad27205a-9c08-11e7-8347-419cd22cfa96.png)
![screenshot_58](https://user-images.githubusercontent.com/19965590/30529173-b0413794-9c08-11e7-837a-2cfb0b5fa06c.png)
